default_language_version:
  python: python3

default_stages: [commit, push]

repos:
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=nd,reacher,thist,ths, ure, referenc
        exclude: >
          (?x)^(
              .*\.csv|
              .*\.ipynb|
          )$
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --ignore=E203,W503,E741
          - --max-complexity=30
          - --max-line-length=456
          - --show-source
          - --statistics
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus", "--keep-runtime-typing"]
